apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: rabbitmq-svc
  labels:
    app: rabbitmq
#    type: NodePort
spec:
  type: NodePort
#  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: http
      port: 15672
      targetPort: 15672
      nodePort: 30010
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30011
